name: MarcFoley
favicon: null
layout_spectrum: 1
typography_spectrum: 0.67027
title: Developer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070803'
    - '#886c60'
    - '#a0a09e'
    - '#bcbebd'
    - '#f9d6a5'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: engagement
    item: 2a6200fe-dd6b-49d8-97b1-643b8ae21f50
    url: null
